run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
    exclude-functions:
      - (net/http.ResponseWriter).Write
      - (*log/slog.Logger).Info
      - (*log/slog.Logger).Debug
      - (*log/slog.Logger).Error
      - (*log/slog.Logger).Warn

  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

  gocyclo:
    min-complexity: 30

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US
    ignore-words:
      - analysed

  lll:
    line-length: 200

  goimports:
    local-prefixes: github.com/sckyzo/eseries_exporter

  gofmt:
    simplify: true

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - assignOp
      - hugeParam
      - rangeValCopy
      - exposedSyncMutex
      - httpNoBody

  revive:
    rules:
      - name: package-comments
        disabled: true
      - name: unused-parameter
        disabled: true
      - name: exported
        disabled: true

  gosec:
    excludes:
      - G104 # Unhandled errors in specific cases (like w.Write)
      - G114 # Use of net/http server without timeouts (will be addressed later)
      - G304 # File path provided as variable (necessary for config loading)
      - G402 # TLS InsecureSkipVerify (configurable option)

  funlen:
    lines: 100
    statements: 50

  depguard:
    rules:
      main:
        deny:
          - pkg: "io/ioutil"
            desc: "io/ioutil is deprecated, use io or os instead"

linters:
  disable-all: true
  enable:
    # Enabled by default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Additional recommended linters
    - bodyclose
    - dogsled
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - lll
    - misspell
    - nakedret
    - nolintlint
    - revive
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - unparam
    - whitespace

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - goconst

    # Exclude known false positives
    - linters:
        - staticcheck
      text: "SA1019:" # Ignore deprecation warnings for now

    - linters:
        - lll
      source: "^//go:generate "

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
